FROM python:3

WORKDIR /usr/src/app

COPY requirements-main.txt ./
COPY requirements-api.txt ./
RUN pip install --no-cache-dir -r requirements-main.txt
RUN pip install --no-cache-dir -r requirements-api.txt

COPY . .

#CMD [ "uvicorn api:app --host 127.0.0.1 --port 8000 --reload" ]
CMD ["uvicorn", "api:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
